language: node_js
node_js:
  - "stable"

sudo: required

before_install:
  - "npm install grunt-cli -g"
  - "npm install selenium-standalone -g"
  - "selenium-standalone install"
  - "npm install -g nightwatch"
  - "selenium-standalone start &"
  - "npm install"
  - "grunt serve &"

script:
  - "nightwatch -e travis --verbose"
