language: node_js
node_js:
  - "stable"
  - "4"
  - "0.12"
  - "0.10"

sudo: required

before_install:
  - "npm install grunt-cli -g"
  - "npm install selenium-standalone -g"
  - "selenium-standalone install"
  - "selenium-standalone start"
  - "npm install -g nightwatch"
  - "npm install"
  - "grunt serve &"

script:
  - "nightwatch -e travis --verbose"
